### ISSUE TITLE
Supported OS list

### ISSUE THREAD

**Issue by L00k3r** [CrowdStrike/aws-ssm-distributor#102]
Current supported OS list has now unsupported OS and missing new supported OS

https://github.com/CrowdStrike/aws-ssm-distributor/blob/main/official-package/README.md

**No longer supported OS**
Amazon Linux 1
CentOS 6
SUSE Linux Enterprise Server 11
Red Hat Enterprise Linux 6

**Supported OS not on list**
Alma Linux
Rocky Linux
Debian 12

**Comment by redhatrises** [comment]
Hello,

Per https://docs.aws.amazon.com/systems-manager/latest/userguide/distributor.html#:~:text=platforms%20and%20architectures.-,Supported%20package%20platforms%20and%20architectures,-You%20can%20use . AWS not currently support Rocky Linux or Alma Linux. Therefore, the list will not show them.

**Comment by ffalor** [comment]
Hey @L00k3r version 2.1.0 of the distributor package now supports these operating systems.
