### ISSUE TITLE
SSM document support for Ubuntu 24.04 not working

### ISSUE THREAD

**Issue by nickjohnsonm** [CrowdStrike/aws-ssm-distributor#105]
The supported O/S table was updated to include Ubuntu 24.04. When using document version 3 of CrowdStrike-FalconSensorDeploy I'm still getting an error installing on 24.04:

```
error: failed to find platform: no manifest found for platform: ubuntu, version 24.04, architecture x86_64

```

Same problem using the new distributor. This example is from us-west-2.

**Comment by ffalor** [comment]
hey @nickjohnsonm i am looking into this

**Comment by NickJohnsonLytx** [comment]
> hey @nickjohnsonm there is an issue with the Ubuntu 24 install related to the API that I am working with the correct teams to fix.
> 
> However, the error you pasted should not happen if the `FalconSensor-CrowdStrike` distributor package was used. I just tested this myself in the us-west-2 region. I used v3 of the `CrowdStrike-FalconSensorDeploy` which used the `FalconSensor-CrowdStrike` package. It was able to find a manifest for platform ubuntu & version 24.04, but failed afterwords with the error I am working with the api teams to fix.
> 
> So verify the correct automation document is running and you can check the run command to verify the correct package `FalconSensor-CrowdStrike` is being consumed. You will still get an error the other issue is resolved, but the error should look like this:
> 
> ```
> No presigned url returned from api call: { "meta": { "query_time": 0.050255583, "pagination": { "offset": 1, "limit": 1, "total": 1 }, "powered_by": "binserv", "trace_id": "sdfsdf" }, "errors": null, "resources": [] }...
> ```

Thanks so much @ffalor , I now see this too.

**Comment by nickjohnsonm** [comment]
> hey @nickjohnsonm there is an issue with the Ubuntu 24 install related to the API that I am working with the correct teams to fix.
> 
> However, the error you pasted should not happen if the `FalconSensor-CrowdStrike` distributor package was used. I just tested this myself in the us-west-2 region. I used v3 of the `CrowdStrike-FalconSensorDeploy` which used the `FalconSensor-CrowdStrike` package. It was able to find a manifest for platform ubuntu & version 24.04, but failed afterwords with the error I am working with the api teams to fix.
> 
> So verify the correct automation document is running and you can check the run command to verify the correct package `FalconSensor-CrowdStrike` is being consumed. You will still get an error the other issue is resolved, but the error should look like this:
> 
> ```
> No presigned url returned from api call: { "meta": { "query_time": 0.050255583, "pagination": { "offset": 1, "limit": 1, "total": 1 }, "powered_by": "binserv", "trace_id": "sdfsdf" }, "errors": null, "resources": [] }...
> ```

Thanks so much @ffalor - I now see this too.

**Comment by ffalor** [comment]
This looks to be resolved on the API side, and I was able to install ubuntu 24 w/o issue. Feel free to reopen if this is still not working for you.

Thanks for reaching out and reporting this.

**Comment by nickjohnsonm** [comment]
I verified this works now, thanks.
