### ISSUE TITLE
Add support for Debian 12 on AWS Official Distributor

### ISSUE THREAD

**Issue by gpapakyriakopoulos** [CrowdStrike/aws-ssm-distributor#107]
Falcon sensor supports Debian 12 for a while but it seems that the AWS Distributor is missing support for Debian 12 which is the current stable version of Debian.

We would really appreciate if the support was added since most of our infrastructure is running on latest Debian.

**Comment by gpapakyriakopoulos** [comment]
Thanks for the quick reply! We've also reached out via CrowdStrike Support since we were unsure if an issue here is enough, apologies for the double spam.

Thank you!

**Comment by ffalor** [comment]
@gpapakyriakopoulos `v2.0.1` of the `FalconSensor-CrowdStrike` package now contains support for Debian 12 x86 & arm64.

No worries about the double spam! Thank you for pointing it! Sorry it was overlooked. Please let me know if there is anything else I can help with.

**Comment by gpapakyriakopoulos** [comment]
I can confirm everything works as expected, you have my deepest thanks!
