### ISSUE TITLE
ExecuteDistributorPackageWindows and ExecuteDistributorPackageLinux remains in Pending state

### ISSUE THREAD

**Issue by drey143** [CrowdStrike/aws-ssm-distributor#59]
Running the automation documents on all our instances but got stuck on "ExecuteDistributorPackageWindows" and/or  ExecuteDistributorPackageLinux step. Every other step is successful as you can see in the output below. This issue applies to all our instances Any suggestions on how to troubleshoot this?

```
69a0d9d8-3784-4bb1-993f-5157413d9fd0 | 1 | GetSSMInstanceInformation | aws:executeAwsApi | Success | Mon, 14 Aug 2023 20:15:15 GMT | Mon, 14 Aug 2023 20:15:16 GMT
-- | -- | -- | -- | -- | -- | --
bd92d07e-be00-4dc4-af25-df1b085f5d59 | 2 | HandlePreqrequisites | aws:executeScript | Success | Mon, 14 Aug 2023 20:15:16 GMT | Mon, 14 Aug 2023 20:15:29 GMT
cae30182-4257-4913-9cb3-7963ee56e0d9 | 3 | BranchExecuteWindowsDistributorPackage | aws:branch | Success | Mon, 14 Aug 2023 20:15:29 GMT | Mon, 14 Aug 2023 20:15:29 GMT
669b539c-410e-4281-a83a-bf24076e7842 | 4 | BranchExecuteLinuxDistributorPackage | aws:branch | Success | Mon, 14 Aug 2023 20:15:30 GMT | Mon, 14 Aug 2023 20:15:30 GMT
181bd85e-ab0a-4460-84df-79f3ffa575d1 | 5 | HandleCleanup | aws:executeScript | Success | Mon, 14 Aug 2023 20:15:30 GMT | Mon, 14 Aug 2023 20:15:43 GMT
7a484ae6-73f5-4f63-937a-25aa490d11fa | 6 | ExecuteDistributorPackageWindows | aws:runCommand | Pending | - | -
df61d95f-09f9-4cc3-a424-9a4fe61f504e | 7 | ExecuteDistributorPackageLinux | aws:runCommand | Pending
```

**Comment by ffalor** [comment]
Hey @drey143 those two steps will always show pending if no instances were targeted ([read more here](https://github.com/CrowdStrike/aws-ssm-distributor/blob/main/official-package/README.md#why-do-some-automation-steps-stay-pending))

What's most likely happening is there are no instances in that region that has Systems Manager correctly setup. Each instance needs the SSM agent, a instance profile with permissions for SSM, and network connectivity back to SSM.

https://docs.aws.amazon.com/systems-manager/latest/userguide/systems-manager-setting-up.html

**Comment by drey143** [comment]
@ffalor the 2 instances in this region are Linux (ubuntu) and Windows which comes with preconfigured SSM agent on the AMIs. Network connectivity was done, hence why the instances are visible in SSM Fleet Manager

**Comment by ffalor** [comment]
What returns from `GetSSMInstanceInformation` step? that step will return the list of instances the ssm api says exists.

For example: if I target all instances (lets say I have 10), and it returns 2 that means out of those 10 AWS thinks only 2 have the required perquisites.

**Comment by drey143** [comment]
@ffalor you are right, the instances are running on Red Hat which doesn't come with a preconfigured SSM agent

**Comment by drey143** [comment]
@ffalor thanks for your quick response
another question I have, is there a similar automation solution in your pipeline for Kubernetes as well to automate CrowdStrike Installation.

**Comment by ffalor** [comment]
We have the [falcon operator ](https://github.com/CrowdStrike/falcon-operator) and we have a [terraform ](https://github.com/CrowdStrike/terraform-kubectl-falcon?q=terr&type=all&language=&sort=)module that can deploy the operator to your clusters.

As far as some form of automation inside the AWS console, there is nothing I am able to talk about right now. Is there something specific you had in mind?

Also marking this issue as closed (we can continue the convo above tho)
