### ISSUE TITLE
Adding Group tagging on CrowdStrike Console while using SSM Distributor

### ISSUE THREAD

**Issue by drey143** [CrowdStrike/aws-ssm-distributor#61]
With the SSM Distributor automation, How can I ensure that the Grouping Tags column has something like "GROUPING TAGS = 
SensorGroupingTags/AWS-Cloud-Env"

**Comment by ffalor** [comment]
You can use `LinuxInstallerParams` and `WindowsInstallerParams` to pass in tags to be added to the sensor at install time.

Something ilke:
`--tags="AWS-Cloud-Env` for linux
`GROUPING_TAGS="AWS-Cloud-Env"` for windows

You can checkout the sensor install docs in the falcon console for more information about the different install parameters

**Comment by drey143** [comment]
@ffalor Thank you, It worked
