### ISSUE TITLE
Ability to target a group of instances without a specified tag

### ISSUE THREAD

**Issue by mattgresham** [CrowdStrike/aws-ssm-distributor#62]
Hi CrowdStrike Team,

I tried looking in both the SSM and CS documentation for the ability to be able to target the distributor at only instances without a specified tag. Is this something that I have missed or is this not possible?

Thanks

**Comment by ffalor** [comment]
Hey @mattgresham, I am not sure that is possible the only 3 targets are all instances, resource group, or tag. Resource group & tag are both targeting machines where a tag has a certain value.
