### ISSUE TITLE
Adding N-2 Package Version causing install to fail

### ISSUE THREAD

**Issue by Aydoxia** [CrowdStrike/aws-ssm-distributor#70]
I have tested on both Linux and Windows installs and it seems specifying package version N-2 is causing the install to fail .

install errors: Unexpected response code: BadRequest Response:
At C:\ProgramData\Amazon\SSM\Packages\FalconSensor-Windows\v1.2.0\install.ps1:141 char:5
+     throw "Unexpected response code: $($resp.StatusCode) Response: $( ...
+     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : OperationStopped: (Unexpected resp...uest Response: :String) [], RuntimeException
    + FullyQualifiedErrorId : Unexpected response code: BadRequest Response:
failed to run commands: exit status 1
Failed to install package; install status Failed

**Comment by ffalor** [comment]
Sorry, I can see how the documentation is confusing and that needs to be clarified.

The `WindowsPackageVersion` and `LinuxPackageVersion` expects the full version you want installed: `7.04.17605` the docs mention the default value is `N-1`, but technically the default value is an empty string and when we see an empty string we grab whatever version is `N-1`

**Comment by Aydoxia** [comment]
@ffalor Thanks for the quick response. I just tried with the full version and can confirm it is working. The updated documentation is more clear as well, thanks!
