### ISSUE TITLE
CrowdStrike-FalconSensorDeploy Automation Document has no Target Type

### ISSUE THREAD

**Issue by JerelMansfield** [CrowdStrike/aws-ssm-distributor#77]
I'm trying to deploy the official distributor package via the automation runbook and selecting rate control.

If I choose InstanceIds as the parameter to branch on with targets set to tags, the runbook will run against all resources with those tags instead of just EC2 instances.

On the CrowdStrike-FalconSensorDeploy document, the target type is empty - is there a way to selectively target resources by tags without it applying to all resources?

**Comment by ffalor** [comment]
Hey @JerelMansfield I think a resource group may be what you want. You can tell a resource group to target any instance with a tag that is of type EC2. Then under rate control you can target the resource group.

![image](https://github.com/CrowdStrike/aws-ssm-distributor/assets/35144141/d25a4634-4939-440f-a829-bd8dfc8110ef)

**Comment by JerelMansfield** [comment]
Ah, perfect call-out.

Yes, that should work!
