### ISSUE TITLE
Official Distributor Package Downloads Incorrect Installer Using Default LinuxPackageVersion

### ISSUE THREAD

**Issue by JerelMansfield** [CrowdStrike/aws-ssm-distributor#79]
Wondering if this is expected behavior.

On an AWS Instance:

- Operating System: Ubuntu 22.04.3 LTS
- Kernel: Linux 5.19.0-1028-aws
- Architecture: x86-64
- Hardware Vendor: Xen
- Hardware Model: HVM domU

Leaving the LinuxPackageVersion empty to use the default N-1 value causes the install script to download the wrong installer:

Output:
```bash
No version specified, grabbing the n-1 version that matches the base filter. Filter: os:'*Ubuntu*'+os_version:'*22*'+os_version:!'*arm64*'+platform:'linux'
Getting installer ...
Running install command (installing /tmp/falcon-sensor_7.05.0-16004_s390x.deb) sensor version: 7.05.16004...
```

When 7.05.0.16004 is used in the LinuxPackageVersion field the correct installer is used:
```bash
Version specified, grabbing the exact version: 7.05.16004. Filter: os:'*Ubuntu*'+os_version:'*22*'+os_version:!'*arm64*'+platform:'linux'+version:'7.05.16004'

Getting installer ...

Running install command (installing /tmp/falcon-sensor_7.05.0-16004_amd64.deb) sensor version: 7.05.16004...
```

**Comment by ffalor** [comment]
@JerelMansfield thanks for reporting this issue. The latest release of the official-distributor package `v1.3.1` fixed this issue. You shouldn't have to do anything to get the new version.
