### ISSUE TITLE
Official package for ap-northeast-3

### ISSUE THREAD

**Issue by takahiro-oda-paypay** [CrowdStrike/aws-ssm-distributor#81]
Hi I try to use the official package for ap-northeast-3 in terraform.

But as you can see, it does not include ap-northeast-3 region support at the moment. (I could not find it in AWS systems manager document in Osaka region either)
locals {
  cs_supported_regions = [
    "us-east-1",
    "us-east-2",
    "us-west-1",
    "us-west-2",
    "af-south-1",
    "ap-east-1",
    "ap-northeast-1",
    "ap-northeast-2",
    "ap-south-1",
    "ap-southeast-1",
    "ap-southeast-2",
    "ca-central-1",
    "eu-central-1",
    "eu-north-1",
    "eu-south-1",
    "eu-west-1",
    "eu-west-2",
    "eu-west-3",
    "me-south-1",
    "sa-east-1",
  ]
  
  Do you have any plan to include ap-northeast-3 region support soon?
  Or I need to create a custom package for the ap-northeast-3 region?

**Comment by ffalor** [comment]
This is in the works, and hopefully will be released soon.

**Comment by ffalor** [comment]
@takahiro-oda-paypay we now have support for these regions!
