### ISSUE TITLE
Custom Binary not able to find sensors

### ISSUE THREAD

**Issue by xomgc3** [CrowdStrike/aws-ssm-distributor#86]
```
% python3 create-package.py -r us-east-1 -b foo
Downloading required files...
Unable to find sensor that matches filter: os:'Amazon Linux'+os_version:'1'+platform:'linux'
```

Has something changed?  I haven't run this script in a few weeks, but it did work the last time that I did.

**Comment by ffalor** [comment]
No changes were made since #80. I haven't updated the main script with error handling could you use the same gist https://gist.github.com/ffalor/5197aa421871e8fc35c889a9f747291e and see if you have the same error?
