### ISSUE TITLE
It does not work when Proxy is specified in WindowsInstallerParams.

### ISSUE THREAD

**Issue by 0weight** [CrowdStrike/aws-ssm-distributor#87]
Hello.
I am using the official package.
I need to use Proxy during installation, so I have put Proxy settings in WindowsInstallerParams, but it does not work well.

I checked the installation script and there seems to be a problem in the process of replacing Proxy settings.

There are not enough arguments in the replace method of app_proxyname, so an error occurs.

```powershell
$proxy = ""

if ($installArguments -match "app_proxyname") {
    Write-Output "Proxy settings detected in arguments, using proxy settings to communicate with the CrowdStrike api"
    foreach ($arg in $installArguments) {
        $field = $arg.Split("=")
        
        if ($field[0] -eq "app_proxyname") {
            $proxy_host = $field[1].Replace("http://", "").Replace("https://") ***This line.***
            Write-Output "Proxy host ${proxy_host} found in arguments"
        }    

        if ($field[0] -eq "app_proxyport") {
            $proxy_port = $field[1]
            Write-Output "Proxy port ${proxy_port} found in arguments"
        }    
    }    

    if ($proxy_port -ne "") {
        $proxy = "http://${proxy_host}:${proxy_port}"
    }    
    else {
        $proxy = "http://${proxy_host}"
    }    

    $proxy = $proxy.Replace("'", "").Replace("`"", "")
    Write-Output "Using proxy: ${proxy} to communicate with the CrowdStrike Apis"
}    

```

**Comment by ffalor** [comment]
Can you provide what you're passing in for WindowsInstallerParams with any sensitive information redacted.

**Comment by 0weight** [comment]
These are not actual values, but are set as in the manual example.

`APP_PROXYNAME=proxy.example.com APP_PROXYPORT=8080`

https://github.com/CrowdStrike/aws-ssm-distributor/blob/main/official-package/README.md#deploying-the-crowdstrike-falcon-sensor

**Comment by 0weight** [comment]
We provide the logs from the AWS Distributor run.

output.txt
```
Initiating FalconSensor-Windows v1.3.1 install
Plugin aws:runPowerShellScript ResultStatus Success
install output: Running install.ps1
Installing Falcon Sensor...
No version specified, grabbing the n-1 version that matches the base filter. Query string: limit=1&offset=1&sort=version&filter=os%3a%27Windows%27%2bplatform%3a%27windows%27
Proxy settings detected in arguments, using proxy settings to communicate with the CrowdStrike api

Successfully installed FalconSensor-Windows v1.3.1
``` 

error.txt
```
install errors: C:\ProgramData\Amazon\SSM\Packages\FalconSensor-Windows\v1.3.1\install.ps1 : Cannot find an overload for "Replace" and 
the argument count: "1".
At C:\ProgramData\Amazon\SSM\InstanceData\i-xxxxxxxxxxxxxxxxx\document\orchestration\xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxxx\configurePackage\v1.3.1\install\_script.ps1:2 char:1
+ .\install.ps1; exit $LASTEXITCODE
+ ~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [install.ps1], MethodException
    + FullyQualifiedErrorId : MethodCountCouldNotFindBest,install.ps1
 


```

**Comment by ffalor** [comment]
thanks for the extra context, i've added this to the teams backlog.

**Comment by ffalor** [comment]
Hey @0weight the latest version of the distributor package `v1.3.2` fixes this issue.

If you are using the latest automation document you do not need to do anything, and the new version will be used on the next run.

You can check if you are using the latest automation document by going to your association and seeing if the version is set to `$DEFAULT`
<img width="815" alt="image" src="https://github.com/CrowdStrike/aws-ssm-distributor/assets/35144141/b5462803-1f6f-4f60-b7e9-f56645d9f722">
