### ISSUE TITLE
Failing to deploy on multiple OU and multiple regions

### ISSUE THREAD

**Issue by LuisVelazquezSolera** [CrowdStrike/aws-ssm-distributor#91]
Hi the template for aws-organizations is failing when I tried to deploy the stackset in multiple organizations units and region, here is the example of my samconfig.toml

`parameter_overrides=[

  # Deployment Scope
  "ProvisionOU=ou-xxxxx-xxxxx,ou-xxxx-xxxx,ou-xxxx-xxxx",
  "Regions=us-east-1,us-west-2,us-west-1",`
  
  I received the following error, EX
  ![sam](https://github.com/CrowdStrike/aws-ssm-distributor/assets/113381280/99f14094-62a3-4224-bcb9-ae74d313d898)

I did not modified anything of the template.yml

**Comment by ffalor** [comment]
@ryanjpayne did #92 resolve this issue?

**Comment by ryanjpayne** [comment]
@LuisVelazquezSolera  [#92](https://github.com/CrowdStrike/aws-ssm-distributor/pull/92) resolves this issue!
