### ISSUE TITLE
Support for AlmaLinux

### ISSUE THREAD

**Issue by adenicola626** [CrowdStrike/aws-ssm-distributor#93]
Add support for AlmaLinux

failed to find platform: no manifest found for platform: almalinux, version 8.9, architecture x86_64`

**Comment by ffalor** [comment]
AWS SSM does not support AlmaLinux for distributor packages. We are unable to publish a distributor pacakge targeting AlmaLinux becaue AWS rejects it. 


For context. https://github.com/CrowdStrike/aws-ssm-distributor/issues/65

**Comment by ffalor** [comment]
Hey @adenicola626,

It looks like aws now supports rocky and alma linux. So I will add support soon, the work will be tracked in #65

**Comment by ffalor** [comment]
Hey @adenicola626 version 2.1.0 of the distributor package now supports these operating systems.
