### ISSUE TITLE
Support for Rocky Linux

### ISSUE THREAD

**Issue by olia-dev** [CrowdStrike/aws-ssm-distributor#94]
Hello,

we are using Rocky Linux (8.9 and higher) and would like to install the Sensor via SSM.

Are there any plans to support this in the future?

**Comment by redhatrises** [comment]
Hello,

Linux distro support is limited to what AWS supports. Currently, Rocky Linux is unsupported by distributor. Please see https://docs.aws.amazon.com/systems-manager/latest/userguide/distributor.html#:~:text=platforms%20and%20architectures.-,Supported%20package%20platforms%20and%20architectures,-You%20can%20use

**Comment by ffalor** [comment]
Hey @olia-dev,

It looks like aws now supports rocky and alma linux. So I will add support soon, the work will be tracked in #65

**Comment by ffalor** [comment]
Hey @olia-dev version 2.1.0 of the distributor package now supports these operating systems.
