### ISSUE TITLE
Event Driven Sensor deployment

### ISSUE THREAD

**Issue by jmckenzie-cs** [CrowdStrike/aws-ssm-distributor#95]
Instead of a scheduled scan for unprotected instances can an event-based method be used? When new instance comes online it will be detected and checked for the Falcon Sensor.  If the sensor is not present it will get deployed to that instance

**Comment by ffalor** [comment]
It is possible to use event bridge to trigger the automation document, so it should be possible. 

Event bridge rule listens for new instances, and when a new instance is created it calls the automation document.

**Comment by ryanjpayne** [comment]
Per AWS,

State Manager also attempts to run the association in the following situations:
...
Target changes – State Manager runs the association after any of the following activity occurs on a target node:
- A managed node comes online for the first time.
- A managed node comes online after missing a scheduled association run.
- A managed node comes online after being stopped for more than 30 days.

see https://docs.aws.amazon.com/systems-manager/latest/userguide/state-manager-about.html for more details
