### ISSUE TITLE
Official AWS Distributor Package in the Falcon agent SSM Document does not include support for Rocky Linux and alma linux

### ISSUE THREAD

**Issue by adesoc24** [CrowdStrike/aws-ssm-distributor#99]
The Official AWS Distributor Package in the Falcon agent SSM Document does not include support for Rocky Linux and Alma linux

https://github.com/CrowdStrike/aws-ssm-distributor/blob/main/official-package/README.md#deploying-the-crowdstrike-falcon-sensor

Please include support for RockyLinux and Alma Linux

https://rockylinux.org/
https://almalinux.org/

**Comment by redhatrises** [comment]
Hello,

Please see https://docs.aws.amazon.com/systems-manager/latest/userguide/distributor.html#:~:text=platforms%20and%20architectures.-,Supported%20package%20platforms%20and%20architectures,-You%20can%20use for SSM supported OSes. AWS not currently support Rocky Linux or Alma Linux.

**Comment by ffalor** [comment]
hey @adesoc24,

It looks like aws now supports rocky and alma linux. So I will add support soon, the work will be tracked in #65

**Comment by adesoc24** [comment]
That's good news. Thanks!
